[platformio]
src_dir = .
default_envs = cardenza
[env:cardputer]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = m5stack-stamps3
framework = arduino
board_build.partitions = default_8MB.csv
board_build.flash_mode = qio
board_build.f_flash = 80000000L
build_src_filter = +<*> -<platform_sdl/> -<tests/> -<test/>
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    m5stack/M5Cardputer@1.1.1
    https://github.com/m5stack/M5Unified.git#8108bfad04a20ff4e57c0751f62dd6fdf6b137a6
    https://github.com/m5stack/M5GFX.git#c64a65e
[env:cardenza]
extends = env:cardputer
build_flags =
    ${env:cardputer.build_flags}
    -DCARDENZA_TARGET=1
    -Wl,--wrap=esp_partition_erase_range
    -Wl,--wrap=_ZN2m511Power_Class5beginEv
    -Wl,--wrap=_ZN2m59M5Unified10_setup_ledEN4lgfx6boards7board_tE
board_upload.flash_size = 8MB
board_build.arduino.memory_type = qio_qspi
